@host = http://localhost:3000/

###

GET {{host}} HTTP/1.1

###

GET {{host}}contact HTTP/1.1

###

GET {{host}}faq HTTP/1.1

###

POST {{host}}/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###